### ISSUE TITLE
Bug for trees with length(class(phy)) > 1

### ISSUE THREAD

**Issue by ChrisHIV** [bcm-uga/apTreeshape#1]
The test `if (class(phy)!='phylo')` in `is.binary.phylo` (and perhaps elsewhere) breaks for tree objects with `length(class(phy)) > 1`. For example the dated trees output by https://github.com/emvolz/treedater have class equal to `c("treedater", "phylo")`. Replacing the test by `if (!is(phy, "phylo"))` worked for me, though there seem to be multiple ways of robustly testing class inheritance in R and I'm not sure what's best.
Cheers

**Comment by mblumuga** [comment]
Tks for the suggestion. It has been changed on github. Will submit an up-to-date version on CRAN later.
